language: node_js
node_js:
- 7.10.0
script: npm run deploy
deploy:
  # TEST
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    target_branch: gh-pages
    local_dir: dist/static
    on:
      branch: feature/travisci # develop
  # PROD
#  - provider: pages
#    skip_cleanup: true
#    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#    target_branch: ???
#    local_dir: dist/static
#    fqdn: www.codestar.nl
#    on:
#      branch: master
